var someDummyText = [
  "Croissant oat cake powder lollipop tiramisu lollipop jelly-o cake. Topping cake biscuit pudding brownie macaroon. Donut marzipan jelly carrot cake chocolate cake cake caramels donut biscuit. Pastry chocolate cake lemon drops croissant jujubes cake dessert. Chupa chups lemon drops cake gummi bears muffin marzipan cotton candy wafer. Lemon drops cookie cheesecake muffin sweet tiramisu tootsie roll liquorice. Jelly-o cookie jujubes dragée chocolate gingerbread liquorice. Wafer sesame snaps danish lollipop jelly-o candy pudding candy canes pie. Chocolate cake bonbon bonbon dessert croissant gingerbread. Tart chocolate bar icing gingerbread jelly bear claw brownie. Lemon drops pudding oat cake gummi bears ice cream biscuit sweet cupcake chupa chups. Bear claw lollipop icing cake powder lemon drops.",

  "Topping macaroon cupcake biscuit jelly-o muffin icing candy. Tart candy canes marshmallow liquorice cotton candy jelly-o lollipop liquorice pie. Lollipop jujubes chocolate cake bonbon topping. Candy oat cake marshmallow sesame snaps jelly-o chocolate bar chocolate. Macaroon icing chocolate cake tart bear claw. Jelly pie pudding carrot cake wafer lollipop shortbread bonbon pudding. Tiramisu cupcake marzipan dragée lemon drops wafer muffin. Tootsie roll marshmallow powder croissant sesame snaps toffee sugar plum ice cream sesame snaps. Brownie soufflé liquorice apple pie sugar plum. Jelly beans pudding gummi bears sweet candy canes candy canes candy ice cream topping. Donut liquorice gummi bears dessert marzipan danish bonbon. Dessert jelly-o apple pie oat cake sweet roll. Cheesecake icing candy canes macaroon shortbread.",

  "Chupa chups chupa chups pastry pie brownie. Powder cotton candy caramels sweet roll chocolate bar sweet roll cheesecake liquorice apple pie. Cotton candy apple pie liquorice fruitcake gingerbread cookie cheesecake. Powder pudding donut muffin apple pie jelly beans croissant brownie pie. Fruitcake dragée sweet marzipan tart chocolate bar chupa chups tart fruitcake. Muffin shortbread macaroon icing cake candy canes powder liquorice jelly-o. Soufflé powder cotton candy sweet roll lollipop marshmallow. Cake tart dessert pie chocolate bar toffee caramels jelly-o. Sweet sugar plum fruitcake liquorice chupa chups. Croissant gingerbread jelly beans apple pie cotton candy chocolate cake. Lollipop sesame snaps sweet roll toffee caramels soufflé carrot cake fruitcake. Pie cheesecake muffin sweet cupcake halvah candy canes. Tiramisu wafer dragée oat cake cookie dessert.",

  "Croissant pastry chocolate tart chocolate cake. Bear claw cookie sesame snaps pie topping sweet roll donut. Caramels candy muffin fruitcake fruitcake jelly beans bear claw halvah jujubes. Cake croissant bear claw fruitcake topping ice cream oat cake. Cheesecake pastry jujubes sweet roll wafer croissant jujubes lemon drops marshmallow. Donut croissant halvah macaroon cake cheesecake marshmallow chocolate bar croissant. Pudding toffee danish powder bonbon cupcake. Tiramisu cake cotton candy gummies chupa chups chupa chups chocolate bar. Donut liquorice chupa chups cake donut cotton candy sweet roll powder croissant. Sesame snaps sugar plum jelly pie ice cream cheesecake gingerbread muffin. Oat cake croissant liquorice croissant brownie toffee cupcake jujubes. Icing chocolate sesame snaps dragée dessert brownie.",

  "Muffin apple pie chupa chups chocolate cake liquorice candy gummi bears. Sweet roll sweet roll halvah caramels carrot cake candy canes croissant. Brownie danish icing bonbon liquorice chocolate cake. Muffin donut jelly beans liquorice cake wafer sweet roll dragée. Bear claw dragée pudding wafer brownie. Sugar plum fruitcake halvah liquorice croissant fruitcake gummi bears. Wafer chocolate chocolate liquorice sesame snaps gummi bears liquorice caramels ice cream. Toffee cake danish apple pie soufflé wafer candy canes cheesecake bear claw. Soufflé jelly beans apple pie oat cake chupa chups pie cookie jelly beans carrot cake. Soufflé sugar plum caramels bonbon cookie sesame snaps chupa chups shortbread. Apple pie marshmallow topping tootsie roll icing chocolate wafer gingerbread sweet. Halvah dessert bear claw cupcake pastry donut cookie bonbon lollipop. Sesame snaps candy marzipan ice cream soufflé ice cream brownie. Topping marzipan apple pie cotton candy tiramisu ice cream gummi bears pie jelly.",

  "Carrot cake halvah cupcake dragée topping lemon drops. Bonbon carrot cake oat cake dragée brownie pie gummi bears. Cupcake bonbon oat cake lemon drops soufflé. Pudding lollipop bear claw oat cake bonbon tootsie roll halvah. Ice cream apple pie lollipop gingerbread gummies. Cake brownie cake liquorice jelly beans. Powder oat cake pie jelly-o donut icing cookie gummi bears. Lollipop tiramisu ice cream shortbread chupa chups. Tiramisu lemon drops sugar plum oat cake powder muffin. Chocolate cheesecake chupa chups danish sweet oat cake sweet chupa chups chocolate bar. Pudding marzipan shortbread wafer chocolate dragée apple pie sugar plum. Lollipop bonbon muffin sweet tootsie roll donut shortbread cake sugar plum. Cupcake caramels chocolate wafer chupa chups lemon drops.",

  "Tiramisu sesame snaps tiramisu cake bear claw shortbread cupcake. Lemon drops muffin candy jelly beans carrot cake sugar plum ice cream cheesecake halvah. Halvah candy jelly-o macaroon dragée dragée sesame snaps gummi bears. Gummi bears bear claw donut cheesecake danish jujubes. Cake chocolate bar cheesecake soufflé soufflé. Shortbread chocolate bar wafer cake tootsie roll. Chocolate jelly beans gummies sugar plum tootsie roll. Sweet pastry cotton candy gummies tootsie roll cookie muffin. Pastry liquorice sweet roll sweet roll candy chocolate cake toffee dragée chocolate. Cake sweet roll chocolate bar cotton candy sesame snaps cake muffin toffee cotton candy. Cheesecake bonbon cheesecake chocolate bar cheesecake. Gingerbread bonbon cupcake macaroon carrot cake. Croissant lemon drops liquorice sugar plum chocolate bar soufflé tootsie roll gummies sweet.",

  "Wafer sesame snaps lemon drops bear claw chupa chups. Cupcake lemon drops brownie icing cake ice cream. Danish pudding brownie wafer candy canes pudding chupa chups wafer jujubes. Gingerbread danish jelly-o chocolate tiramisu apple pie pastry jujubes cake. Muffin jelly-o bonbon gummies pastry. Chupa chups cake cotton candy donut apple pie brownie. Gummies pie cake chocolate cake icing. Cake apple pie gingerbread tiramisu jelly-o. Oat cake jelly carrot cake dragée bonbon cookie fruitcake toffee tiramisu. Icing apple pie chocolate cake bear claw cake halvah bear claw chocolate bear claw. Danish sweet biscuit donut shortbread. Cheesecake danish dessert gummi bears cotton candy fruitcake marshmallow.",

  "Sesame snaps jelly lollipop powder dragée marshmallow candy canes macaroon. Biscuit carrot cake tootsie roll chocolate bar sugar plum carrot cake sweet roll marzipan. Carrot cake croissant dragée dessert dessert sesame snaps. Marshmallow chupa chups pie lemon drops candy fruitcake dessert. Dessert cupcake tart tootsie roll chocolate cake icing cake chocolate bar chocolate cake. Sugar plum danish liquorice candy canes halvah sweet apple pie. Gingerbread shortbread bear claw chupa chups chocolate cake tiramisu. Jujubes liquorice wafer bear claw tootsie roll pie danish sweet. Caramels soufflé lemon drops muffin croissant. Cake caramels chocolate bar jelly-o biscuit apple pie. Candy pastry cotton candy tiramisu cake croissant oat cake. Cake sugar plum cheesecake halvah pudding cotton candy macaroon cheesecake bear claw. Gummi bears sesame snaps carrot cake cheesecake pie. Tart brownie shortbread tart cake.",

  "Powder cupcake fruitcake candy jelly-o. Pie dragée sesame snaps chocolate cupcake. Lollipop pudding jujubes apple pie tiramisu caramels biscuit muffin cake. Tart halvah candy canes sesame snaps chocolate bar. Sesame snaps oat cake toffee danish chocolate gummi bears chupa chups topping donut. Sesame snaps gingerbread brownie sweet roll candy canes tart. Cupcake sweet roll lollipop chupa chups gingerbread candy canes sweet. Cake jelly ice cream jelly marshmallow gummies cupcake. Fruitcake muffin dragée jelly beans powder. Brownie wafer cheesecake toffee lollipop. Fruitcake jujubes marshmallow dessert oat cake chocolate cake jelly-o ice cream dessert. Jelly chupa chups cupcake soufflé sweet. Sesame snaps liquorice jelly-o pastry dessert chupa chups. Toffee toffee pie brownie cake lemon drops pie.",

  "Jelly beans pudding liquorice bonbon donut. Candy canes croissant soufflé cheesecake chupa chups danish cheesecake marshmallow chocolate bar. Sweet roll cheesecake carrot cake croissant toffee tart. Fruitcake gummi bears lemon drops pie sesame snaps cheesecake chocolate chocolate bar. Marshmallow cupcake cake cookie chupa chups shortbread fruitcake cotton candy muffin. Jelly wafer carrot cake cake tootsie roll tart gummi bears jelly-o oat cake. Gummi bears sweet cake cake lollipop. Tootsie roll muffin bear claw candy canes fruitcake. Dragée gummi bears chocolate bar brownie marzipan cake. Dragée brownie bear claw jujubes sweet roll gingerbread. Donut toffee topping apple pie fruitcake chocolate cheesecake wafer cake. Shortbread ice cream bear claw macaroon croissant marshmallow. Powder cookie chocolate bar marzipan gummi bears cheesecake marzipan shortbread. Pastry gummi bears sesame snaps sesame snaps sesame snaps.",

  "Fruitcake sweet jelly-o sweet brownie bonbon fruitcake sesame snaps dragée. Powder cookie biscuit jelly-o fruitcake croissant cheesecake. Gummies jelly beans lollipop cookie halvah tart bear claw. Jujubes dragée lemon drops lollipop candy canes bonbon jujubes muffin cake. Pastry bonbon jelly cotton candy macaroon apple pie sweet roll bear claw. Cake jelly beans chocolate bar wafer fruitcake. Halvah jelly lemon drops pie donut. Macaroon tiramisu jelly-o macaroon cake brownie. Chocolate cake jelly icing dragée cake. Chocolate wafer danish bear claw sugar plum. Liquorice apple pie icing sweet croissant powder gingerbread lollipop shortbread. Tootsie roll powder sesame snaps pudding sesame snaps brownie donut halvah jelly-o. Pie lemon drops gummi bears jelly candy canes gummi bears liquorice chocolate bar. Lollipop candy dessert lemon drops candy candy canes chocolate bar.",
];

// finding

var form = document.querySelector("#form");
var portion = document.querySelector("#portion");
var res = document.querySelector("#res");

// add event listener

form.addEventListener("submit", function (e) {
  e.preventDefault();

  var value = parseInt(portion.value);
  var random = Math.floor(Math.random() * someDummyText.length);

  if (isNaN(value) || value <= 0 || value > 12) {
    res.innerHTML = `<p>${someDummyText[random]}</p>`;
  } else {
    var arraySlice = someDummyText.slice(0, value);
    var totalArray = arraySlice
      .map(function (singleDummyText) {
        return `<p>${singleDummyText}</p>`;
      })
      .join("");
    res.innerHTML = totalArray;
  }
});
